'on': 
  workflow_dispatch:
  schedule:
    - cron: 25 5 * * 1

name: pfaedle-stats-test

jobs:
  build_pfaedle:
    parochial_merge: jobs/build_pfaedle

  download_and_prepare_osm:
    parochial_merge: jobs/download_and_prepare_osm

  download_and_prepare_atoc:
    parochial_merge: jobs/download_and_prepare_atoc

  download_and_prepare_tnds:
    parochial_merge: jobs/download_and_prepare_tnds

  download_and_prepare_bods:
    parochial_merge: jobs/download_and_prepare_bods

  merge_and_pfaedle_gtfs:
    parochial_merge: jobs/merge_and_pfaedle_gtfs
