---
title: "Wales-ish OpenTripPlanner Graph"
output:
  md_document:
    variant: gfm-yaml_metadata_block
    preserve_yaml: false
    toc: false
    pandoc_args: ["--wrap=preserve"]
---

You can [read more about this OpenTripPlanner network graph here](https://stupidpupil.github.io/wales_ish_otp_graph).

You can [see the scripts used to download source data and generate it here](https://github.com/stupidpupil/wales_ish_otp_graph).

## License
The *graph.obj* and *network.dat* graph files are made available under the [ODbL v1.0](https://opendatacommons.org/licenses/odbl/1-0/) by Adam Watkins as part of the [Wales-ish OTP graph project](https://stupidpupil.github.io/wales_ish_otp_graph).

The graph files contain:

- street map information obtained from [OpenStreetMap contributors](https://www.openstreetmap.org/copyright), via [Geofabrik.de](https://download.geofabrik.de/europe/great-britain.html), under the [ODbL v1.0](https://opendatacommons.org/licenses/odbl/1-0/),
- heavy rail timetable information obtained from [RSP Limited (Rail Delivery Group)](http://data.atoc.org/) under the [CC-BY v2.0](https://creativecommons.org/licenses/by/2.0/uk/legalcode), and
- bus and other public transport services timetable information obtained from [Traveline](https://www.travelinedata.org.uk/traveline-open-data/traveline-national-dataset/) and the [UK Department for Transport](https://data.bus-data.dft.gov.uk/) under the [OGL v3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/).
- [*Terrain 50* topology data](https://www.ordnancesurvey.co.uk/business-government/products/terrain-50) obtained from Ordnance Survey under the [OGL v3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/).

Each graph file is provided without any warranty of any kind and without any endorsement by any of the individuals or organisations named above, for any purpose.

If you provide a routing service or similar using either graph file you should make sure that the above attributions are stated clearly. If you produce a set of routing instructions using such a routing service, these likely form a "derived database" and should also be provided under the [ODbL v1.0](https://opendatacommons.org/licenses/odbl/1-0/), again with the attributions above attached.

*otp.jar* is a copy of the version of [OpenTripPlanner](https://github.com/opentripplanner/OpenTripPlanner) used to generate the graph file; it is released under the [LGPL v3.0 (or later)](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/LICENSE). Again, it is provided without any warranty of any kind and without any endorsement, for any purpose.

## Guide to release assets

### otp_and_graph.zip

A copy of [OpenTripPlanner](https://github.com/opentripplanner/OpenTripPlanner) and a pre-generated network 'graph' for use with it. Use this to get going quickly with your own instance of OpenTripPlanner. 

You will need to [install Java 17](https://adoptium.net) to run OpenTripPlanner.

### gtfs_and_osm.zip

Public transport and map data in the commonly used [GTFS](https://en.wikipedia.org/wiki/General_Transit_Feed_Specification) and [OSM PBF](https://wiki.openstreetmap.org/wiki/PBF_Format) formats. Many trip planning and transport analysis programs will accept these files. Use this if you want to analyse the timetables yourself or alter them and generate your own network graph.

### r5r_network_dat.zip

A network 'graph' for use with the *[{r5r}](https://github.com/ipeaGIT/r5r)* R package. See [this gist for an example of how to get started with this](https://gist.github.com/stupidpupil/cb60575c5add1b28f0146ff2802424c1). *{r5r}* is usually a better choice than OpenTripPlanner for analyses involving large numbers of journeys.
